server:
   port: 8080
   servlet:
      context-path: /ShopmeAdmin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: happy
  jpa:
    hibernate:
      ddl-auto: update #We use this property ddl-auto to tell Hibernate framework to create the tables in the database from the entity classes.
    show-sql: true   # we use this property to show the SQL statements in the console.
    properties:
      hibernate:
         format_sql: true # we use this property to tell Hibernate framework to make the SQL statements more readable in the console.
         dialect: org.hibernate.dialect.MySQL8Dialect   # we need to specify the database dialect So Hibernate will be able to create the tables properly.


# Dialect is a class that acts as a bridge between Java JDBC types and SQL types, which contains the mapping between java language data type and database datatype. Dialect allows Hibernate to generate SQL optimized for a particular relational database.
# Hibernate generates queries for the specific database based on the Dialect class. A hibernate dialect gives information to the framework of how to convert hibernate queries(HQL) into native SQL queries.